name: Upload to YouTube V2

on:

  workflow_dispatch:
    inputs:
      video_url:
        description: "URL of the video to download"
        required: true
        type: string
      thumbnail_url:
        description: "URL of the thumbnail to download"
        required: false
        type: string
        default: ''
      metadata:
        description: "YouTube metadata in JSON format"
        required: true
        type: string

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:


      - name: checkout this repo
        uses: actions/checkout@v2


      - name: download video from url
        run: |
            wget -O ./video.mp4 "${{ github.event.inputs.video_url }}"


      - name: Write metadata to file
        run: |
          echo '${{ github.event.inputs.metadata }}' | jq '.' > metadata2.json
          cat metadata2.json

      - name: Parse metadata 
        run: |
          cat metadata2.json | sed 's/rnrn/\\r\\n\\r\\n/g' | sed 's/\.rn/\\r\\n/g' | sed 's/:rn/\\r\\n/g' | sed 's/\nnnn/\\r\\n\\r\\n/g' | jq '.' > metadata.json

      # - name: Download thumbnail
      #   run: |
      #     url="${{ github.event.inputs.video_url }}"
      #     domain=$(echo "$url" | sed -E 's|(https?://[^/]+).*|\1|')
      #     path=$(echo "$url" | sed -E 's|https?://[^/]+/||')
      #     num=$(echo "$path" | sed -E 's/.*_([0-9]+)-.*/\1/')
      #     modified_path="${path%.*}_$num-16_9.png"
      #     final_path=$(echo "$modified_path" | sed 's|/|/screenshots/|')
      #     final_url="$domain/$final_path"
      #     echo "Final download URL: $final_url"
      #     wget -O ./thumbnail.png "$final_url"

      - name: Download thumbnail
        run: |
          wget -O ./thumbnail.png "${{ github.event.inputs.thumbnail_url }}"


      # ╭───────────────────────────────────────────────────────╮
      # │                          SSH                          │
      # ╰───────────────────────────────────────────────────────╯
      # - name: 🪲 DEBUG - Setup upterm session
      #   uses: lhotari/action-upterm@v1


      - name: Setup YouTube Uploader
        uses: AnimMouse/setup-youtubeuploader@v2
        with:
          client_secrets: ${{ secrets.CLIENT_SECRETS_B64 }}
          request_token: ${{ secrets.REQUEST_TOKEN_B64 }}


      - name: Run YouTube Uploader
        run: |
            youtubeuploader \
              -debug \
              -secrets $RUNNER_TEMP/client_secrets.json \
              -cache $RUNNER_TEMP/request.token \
              -filename video.mp4  \
              -thumbnail thumbnail.png \
              -metaJSON metadata.json   \
              -metaJSONout metaout.json \


      - name: output metadata returned
        run: |
            cat metaout.json





      # ╭──────────────────────────────────────────────────────────────────────────╮
      # │                                                                          │░
      # │                                                                          │░
      # │                                DEBUGGERS                                 │░
      # │                                                                          │░
      # │                                                                          │░
      # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

      # ╭───────────────────────────────────────────────────────╮
      # │                         HTTP                          │
      # ╰───────────────────────────────────────────────────────╯
      # - uses: dsmirc/ngrok-tunnel-action@cd
      #   name: 🪲 DEBUG - Setup NGROK Tunnel
      #   with:
      #     timeout: 1h
      #     port: 8080
      #     ngrok_authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     tunnel_type: http
      #     save_url_to_filename: tunnelURL.md

      # ╭───────────────────────────────────────────────────────╮
      # │                          SSH                          │
      # ╰───────────────────────────────────────────────────────╯
      # - name: 🪲 DEBUG - Setup upterm session
      #   uses: lhotari/action-upterm@v1