name: Upload to YouTube V2

on:

  workflow_dispatch:
    inputs:
      video_url:
        description: "URL of the video to download"
        required: true
        type: string
      thumbnail:
        description: "URL of the thumbnail to download"
        required: false
        type: string
        default: ''
      metadata:
        description: "YouTube metadata in JSON format"
        required: true
        type: string

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:


      - name: checkout this repo
        uses: actions/checkout@v2


      - name: download video from url
        run: |
            wget -O ./video.mp4 "${{ github.event.inputs.video_url }}"
            wget -O ./thumbnail.png "${{ github.event.inputs.thumbnail }}"


      - name: Write metadata to file
        run: |
          echo '${{ github.event.inputs.metadata }}' | sed 's/\\n//g; s/\\t//g; s/\\"/"/g; s/\\//g; s/^.\(.*\).$/\1/' | jq '.' > metadata.json
          cat metadata.json | sed 's/.rn/\r\n/' | sed 's/rnrn/\r\n\r\n/' | jq '.' > metadata.json
          cat metadata.json 

      # ╭───────────────────────────────────────────────────────╮
      # │                          SSH                          │
      # ╰───────────────────────────────────────────────────────╯
      - name: 🪲 DEBUG - Setup upterm session
        uses: lhotari/action-upterm@v1


      - name: Setup YouTube Uploader
        uses: AnimMouse/setup-youtubeuploader@v2
        with:
          client_secrets: ${{ secrets.CLIENT_SECRETS_B64 }}
          request_token: ${{ secrets.REQUEST_TOKEN_B64 }}


      - name: Run YouTube Uploader
        run: |
            youtubeuploader \
              -debug \
              -secrets $RUNNER_TEMP/client_secrets.json \
              -cache $RUNNER_TEMP/request.token \
              -filename video.mp4  \
              -thumbnail thumbnail.png \
              -metaJSON metadata.json   \
              -metaJSONout metaout.json \


      - name: output metadata returned
        run: |
            cat metaout.json





      # ╭──────────────────────────────────────────────────────────────────────────╮
      # │                                                                          │░
      # │                                                                          │░
      # │                                DEBUGGERS                                 │░
      # │                                                                          │░
      # │                                                                          │░
      # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

      # ╭───────────────────────────────────────────────────────╮
      # │                         HTTP                          │
      # ╰───────────────────────────────────────────────────────╯
      # - uses: dsmirc/ngrok-tunnel-action@cd
      #   name: 🪲 DEBUG - Setup NGROK Tunnel
      #   with:
      #     timeout: 1h
      #     port: 8080
      #     ngrok_authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     tunnel_type: http
      #     save_url_to_filename: tunnelURL.md

      # ╭───────────────────────────────────────────────────────╮
      # │                          SSH                          │
      # ╰───────────────────────────────────────────────────────╯
      # - name: 🪲 DEBUG - Setup upterm session
      #   uses: lhotari/action-upterm@v1